import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Coustard ,Red_Rose,Calistoga,Roboto} from "next/font/google"
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
const coustard = Roboto({
  weight: ['400'],
  style: ['normal',],
  subsets: ['latin'],
  display: 'swap',
})


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GFG VIT-AP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={coustard.className}>
        <Navbar></Navbar>
        {children}</body>
        <Footer></Footer>
    </html>
  );
}
